---
# This Ansible playbook is designed to set up a fresh Ubuntu system with a variety of software tools and utilities.
- name: Setup a fresh Ubuntu system
  hosts: all  # Specifies that the playbook should run on all hosts in the inventory.
  become: yes  # Enables privilege escalation (sudo), necessary for installing packages.

  tasks:  # List of tasks to be executed on the host(s).
  
    # Install basic utilities like curl, wget, git, and text editors (vim, nano).
    - name: Install basic utilities
      apt:
        name:
          - curl
          - wget
          - git
          - vim
          - nano
        state: latest  # Ensures the latest version of the package is installed.

    # Install Python 3 and PIP, the Python package manager.
    - name: Install Python and PIP
      apt:
        name:
          - python3
          - python3-pip
        state: latest

    # Update the apt cache to ensure we are getting the latest versions of packages.
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 86400 # Cache is valid for a day (specified in seconds).
        
    # Install Node.js and NPM, a JavaScript runtime and package manager.
    - name: Install Node.js and NPM
      apt:
        name:
          - nodejs
          - npm
        state: latest

    # Install Java Development Kit (default JDK for Ubuntu).
    - name: Install Java
      apt:
        name: default-jdk
        state: latest

    # Install C and C++ compilers (gcc and g++).
    - name: Install C/C++ compilers
      apt:
        name:
          - gcc
          - g++
        state: latest

    # Install popular web servers - Nginx and Apache.
    - name: Install web servers
      apt:
        name:
          - nginx
          - apache2
        state: latest

    # Install database management systems - MySQL and PostgreSQL.
    - name: Install databases
      apt:
        name:
          - mysql-server
          - postgresql
        state: latest

    # Install system monitoring tools like htop, nmon, and net-tools.
    - name: Install system monitoring tools
      apt:
        name:
          - htop
          - nmon
          - net-tools
        state: latest

    # Install security tools like ufw (Uncomplicated Firewall) and fail2ban.
    - name: Install security tools
      apt:
        name:
          - ufw
          - fail2ban
        state: latest

    # Install rsync, a tool for efficiently transferring and synchronizing files.
    - name: Install backup tools
      apt:
        name: rsync
        state: latest

    # Install Docker and Docker Compose for container management.
    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker
          - docker-compose
        state: latest

    # Install Ansible for automation.
    - name: Install DevOps tools
      apt:
        name:
          - ansible
        state: latest
        
    # Add the HashiCorp GPG key for installing packages from their repository.
    - name: Add HashiCorp GPG key
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
        
    # Add the HashiCorp repository for installing Terraform.
    - name: Add HashiCorp repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
        state: present
        update_cache: yes
        
    # Install Terraform for infrastructure as code.
    - name: Install Terraform
      ansible.builtin.apt:
        name: terraform
        state: latest
        update_cache: yes

    # Install session management tools - screen and tmux.
    - name: Install session management tools
      apt:
        name:
          - screen
          - tmux
        state: latest

    # Install tools for working with archives (zip, unzip, tar).
    - name: Install archive tools
      apt:
        name:
          - zip
          - unzip
          - tar
        state: latest



        
